# Build Settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "The Second Breakfast Podcast"
description: "Stories about food and fitness technologies, about moving and monitoring our bodies."
alt_description: "How We Get Through the Mo(u)rning"
subtitle: "Stories"

email: "audrey.watters@gmail.com"
logo: "/assets/images/egg.png"
logo2: "/assets/images/egg.png"
cover: "/assets/images/cover.jpg"
covercredits: "http://2ndbreakfast.substack.com"

name: "Second Breakfast"
author: "Audrey Watters"
author_image: "/assets/images/author.jpg"
author_email: "audrey.watters@gmail.com"

keywords: 'technology, politics, sports, fitness, food'

paginate:	5
paginate_path: "/blog/page:num"
permalink: "/:categories/:year/:month/:day/:title"

url: "http://2ndbreakfast.me" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@contrafabulists'

# social icons and sharing options
social:
#  - icon:   twitter
#    url:    https://twitter.com/contrafabulists
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&url="

#  - icon:   facebook
#    url: https://facebook.com/contrafabulists  
#    desc: Like me on facebook
#    share_url: http://www.facebook.com/sharer/sharer.php
#    share_title: ?title=
#    share_link: "?u="

#  - icon:   github
#    url:    https://github.com/Contrafabulists/podcast
#    desc:   Fork me on github
#    share_url:
#    share_title:
#    share_link:

 # - icon:  google-plus
 #   url:
 #   desc:
 #   share_url:
 #   share_title:
 #   share_link:

  - icon: rss
    url:  http://2ndbreakfast.me/blog.xml
    desc: Subscribe
    share_url:
    share_title:
    share_link:

  - icon: envelope
    url:  mailto:audrey.watters@gmail.com
    desc: Email
    share_url:
    share_title:
    share_link:
